context:
  name: lua-language-server
  version: 3.16.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/LuaLS/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}-submodules.zip
  sha256: de8d82d3e368a064190b6c335e77c28bc50446f50cd0c421be4a823d77d0b019

build:
  number: 0
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - coreutils
    - diffutils

tests:
  - script:
      - lua-language-server --version

about:
  license: MIT
  license_file: LICENSE
  summary: A language server that offers Lua language support - programmed in Lua
  homepage: https://luals.github.io
  repository: https://github.com/sumneko/lua-language-server

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
