context:
  name: lua-language-server
  version: "3.17.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/LuaLS/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}-submodules.zip
  sha256: 76b1b04ce582a26a4d7e3db0b8e55545e3fce202e5afb6be3141804cdcb3cc18

build:
  number: 0
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - coreutils
    - diffutils

tests:
  - script:
      - lua-language-server --version

about:
  license: MIT
  license_file: LICENSE
  summary: A language server that offers Lua language support - programmed in Lua
  homepage: https://luals.github.io
  repository: https://github.com/sumneko/lua-language-server

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
