context:
  version: "3.18.2"

package:
  name: lua-language-server
  version: ${{ version }}

source:
  url: https://github.com/LuaLS/lua-language-server/releases/download/${{ version }}/lua-language-server-${{ version }}-submodules.zip
  sha256: cfb54fdf1d812e284477cb2e2d68a40de8b1c33e68e9073dd5d9d83165d97b33

build:
  number: 0
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - coreutils
    - diffutils

tests:
  - script:
      - lua-language-server --version

about:
  license: MIT
  license_file: LICENSE
  summary: A language server that offers Lua language support - programmed in Lua
  homepage: https://luals.github.io
  repository: https://github.com/sumneko/lua-language-server

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
