context:
  name: lua-language-server
  version: 3.16.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/LuaLS/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: d214ef43b593a671c1ab17fbff33fc8abc766fa824eebf190690778432253e1b

build:
  number: 0
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - coreutils
    - diffutils

tests:
  - script:
      - lua-language-server --version

about:
  license: MIT
  license_file: LICENSE
  summary: A language server that offers Lua language support - programmed in Lua
  homepage: https://luals.github.io
  repository: https://github.com/sumneko/lua-language-server

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
