context:
  name: lua-language-server
  version: "3.18.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/LuaLS/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}-submodules.zip
  sha256: 9a083114bcf99b3f575176f2024b9aec805ca96b76c8a5ae17340befb7b6a1d7

build:
  number: 0
  script: build.sh
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - coreutils
    - diffutils

tests:
  - script:
      - lua-language-server --version

about:
  license: MIT
  license_file: LICENSE
  summary: A language server that offers Lua language support - programmed in Lua
  homepage: https://luals.github.io
  repository: https://github.com/sumneko/lua-language-server

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
